### ISSUE TITLE
[BUG] 1.20.1 Does not like Summoning Rituals Mod

### ISSUE THREAD

**Issue by Joshernoob** [Armourers-Workshop/Armourers-Workshop#459] opened 2024-03-31 21:46 UTC
description:
in 1.20.1 All versions of the mod, i went threw them 1 by 1, grovey mod loader loads up and then my game crashes. Removing this mod fixes this.

1. Have this mod and Grovy Mod Loader Core
2. Launch game
3. game will Crash after few seconds

Expected behavior
load in with both mods, as grovy mod loader core is just that only a core.

Screenshots
N/A

Debug crash log
https://pastebin.com/JkrDnbx8 - debug
https://pastebin.com/KsZ96LCU - log

Additional context
pastbin only lets you have so much so in them so only end of the debug and full log

**Comment by SAGESSE-CN** [comment] 2024-04-01 13:19
<img width="854" alt="image" src="https://github.com/Armourers-Workshop/Armourers-Workshop/assets/6903353/14141195-dea0-4f3c-a900-65c107cc374e">
is work normaly

**Comment by Joshernoob** [comment] 2024-04-01 22:36
> <img alt="image" width="854" src="https://private-user-images.githubusercontent.com/6903353/318444363-14141195-dea0-4f3c-a900-65c107cc374e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMTEyMDAsIm5iZiI6MTcxMjAxMDkwMCwicGF0aCI6Ii82OTAzMzUzLzMxODQ0NDM2My0xNDE0MTE5NS1kZWEwLTRmM2MtYTkwMC02NWMxMDdjYzM3NGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDFUMjIzNTAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWZkMWEzMGE4ZjgwOGEyOTgzZDUzNGJmOGVmNWRkYWMwYzExNzMyM2EyMTE2OTdlMjEyMWQzY2IwOTg5MWNmOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.L6N7rSJyiPghie9n8LIi8OhCUWC5XRqGLKZ5BNfLwpg"> is work normaly

was only thing that loaded fully on crash for me as the log ad debug do show

**Comment by Joshernoob** [comment] 2024-04-01 22:37
not saying your wrong but i have 362 mods and none of the listed ones that are known to not work so

**Comment by SAGESSE-CN** [comment] 2024-04-02 00:37
you have too many mod, and there is no evidence that this is related to aw at present. 

you need to reduce the mods to confirm that it is caused by aw.

the specific step is to keep only aw and gml mods for startup, and then gradually restore your mod when you can ensure that it starts correctly. 

when you can't start it, you need to record the mod name, and then test the startup of only aw and this mod (and it dependents).

**Comment by Joshernoob** [comment] 2024-04-02 00:54
> you have too many mod, and there is no evidence that this is related to aw at present.
> 
> you need to reduce the mods to confirm that it is caused by aw.
> 
> the specific step is to keep only aw and gml mods for startup, and then gradually restore your mod when you can ensure that it starts correctly.
> 
> when you can't start it, you need to record the mod name, and then test the startup of only aw and this mod (and it dependents).

After copying the pack and disabling mods until the new copy works i've found out the mod the not working with tis one is 

Summoning Rituals

this has been tested in an intance with just the 2 mods threw curseforge app to confirm i hate latest (stable) update for both mods

**Comment by SAGESSE-CN** [comment] 2024-04-02 01:04
https://github.com/AlmostReliable/summoningrituals/issues/28

look like this

**Comment by SAGESSE-CN** [comment] 2024-04-02 03:13
fixed in 2.1.1

**Closed by SAGESSE-CN** 2024-04-02 03:13 UTC
Labels: bug
